language: ruby
rvm:
- 2.4.1
services:
- postgresql
before_script:
- psql -c 'create database koroibos_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: RIj8gqn4Ms/uQIcnoSeKjPNP22qSuLA4BsEjfvjD+H1j21/BzuMtllAfaJpOhjNrNDcKn74fH3OzKWDwgUvqh27kTfx7LNJL4YETt0u8jyN+oJSrjoYhFOA7hFf3uwv41TgTUbMUfeMhQbnf4Elah8KOqi8GSLyQRm24La3ltjvUuG0aKbRgodxmeskyLIxqWkHied90SgfN9+WRujw1bCBSnvZA2Y8baJCJTJ7iUdtfOgK5+KKlaNvTB/oeEEfpTxSGmIZa10uj3gw/VnVGZMjU/jTtW5MXbJ4FVwoKvjGs5CgmbcZo48doHkzEY8T7jJF0XDcSgG4Z2R1vHV0ldrT9eS0k7OtVhThR/OLFzVerwcOJafx6EeFibQapkDv1gkWK9cXAA+vGzX3auQvydg2Y03hlIaYsABKirVbhy6KtPWtEAFczdhG+DIUE3L1hMeS6WhOb8c+VXDih7KZ3UHZy64dnnwJNNwJ20pLAhQyiRLs0K80YVkHxf84gaV9pmQv2KsX+zwTxZFvZpjgkZEzpkxxdQwLjV9Dh4SEqCYsDyZx38cEM/zTn7NAbUBqFcI1NRPU1uThbQCDqj3YDpLevKYJNY4uFLRpqdfnDt41Q7wKLqH0lBcPE+nZOz7HaK634rhjhVzP/IUcN/GD6LArhAI2SbExYKwbCR2f2/xs=
  app: serene-reaches-07094
  on:
    repo: froydroyce/koroibos
